apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z database-service 3306; do echo waiting for db; sleep 5; done;']
      containers:
      - name: keycloak
        image: docker.io/samarsassi/keycloak:24.0.2
        args: ["start-dev"]
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HOSTNAME_URL
          value: "http://keycloak-service:8080"
        - name: KC_HOSTNAME_ADMIN_URL
          value: "http://keycloak-service:8080"
        - name: KC_DB
          value: "mariadb"
        - name: KC_DB_URL
          value: "jdbc:mariadb://database-service.default.svc.cluster.local:3306/recrutement2"
        - name: KC_DB_USERNAME
          value: "root"
        - name: KC_DB_PASSWORD
          value: "root"
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-pvc
